In [1]:
import numpy

In [2]:
# 1. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array. 

original_list = [12.23, 13.32, 100, 36.32]
numpy_arr = numpy.array(original_list)          
print("original_list:", original_list)
print("one-D numpy array:", numpy_arr)

original_list: [12.23, 13.32, 100, 36.32]
one-D numpy array: [ 12.23  13.32 100.    36.32]


In [4]:
# 2. Create a 3x3 matrix with values ranging from 2 to 10.

value = numpy.arange(2, 11).reshape(3,3)        
print("3*3 matrix: \n",value)

3*3 matrix: 
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [6]:
# 3. Write a Python program to create a null vector of size 10 and update sixth value to 11.

arr = numpy.zeros(10)
print(arr)
arr[6] = 1                                      
print("After updating:",arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After updating: [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


In [7]:
# 4. Write a Python program to reverse an array (first element becomes last). 

org_list = [12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37]
org_arr = numpy.array(org_list)
rev_arr = org_arr[::-1]                        
print("Original array:", org_arr)
print("Reversed array:", rev_arr)

Original array: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reversed array: [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [11]:
# 5. Write a Python program to create a 2d array with 1 on the border and 0 inside. 

array_2d  =  numpy.ones((5,5), dtype = int)      # printing 2d array
print("2D array:",array_2d)
array_2d[1:-1, 1:-1] = 0                         # adding 1 on border and 0 inside
print("After adding border:\n",array_2d)

2D array: [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
After adding border:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [10]:
# 6. Write a Python program to add a border (filled with 0's) around an existing array. 

array_2d  =  numpy.ones((3,3), dtype = int)
print(array_2d)
numpy.pad(array_2d, ((1,1),(1,1)), 'constant')   # to add border against existing array

[[1 1 1]
 [1 1 1]
 [1 1 1]]


array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

In [12]:
# 7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard 

board = numpy.zeros((8, 8), dtype = int)
board[1::2, ::2] = 1
board[::2, 1::2] = 1                         # creating 8*8 matrix and printing checkerboard pattern
print("Checker board pattern:")
for m in range(8):
    for n in range(8):
        print(board[m][n], end=" ")
    print()

Checker board pattern:
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 


In [16]:
# 8. Write a Python program to convert a list and tuple into arrays. 

list_ele = [1,2,3,4,5,6]
print("list:",list_ele)                                     # converting list into array
print("list to array:")
array_list = numpy.array(list_ele)
print(array_list)
tuple_ele = ((1,2,3),(4,5,6))
print("tuple:",tuple_ele)                                   # converting tuple into array
print("tuple to array:")
arr = numpy.array(tuple_ele)
print(arr)

list: [1, 2, 3, 4, 5, 6]
list to array:
[1 2 3 4 5 6]
tuple: ((1, 2, 3), (4, 5, 6))
tuple to array:
[[1 2 3]
 [4 5 6]]


In [17]:
# 9. Write a Python program to append values to the end of an array. 

org_arr = numpy.array([10,20,30])
print("Original array:", org_arr)                  
arr = numpy.append(org_arr, [40,50,60,70,80])
print("After appending:", arr)                              # appending values at the end of array

Original array: [10 20 30]
After appending: [10 20 30 40 50 60 70 80]


In [18]:
# 10. Write a Python program to find the real and imaginary parts of an array of complex 

com_num = [1.00000000+0.j, 0.70710678+0.70710678j] 
com_arr = numpy.array(com_num)
print(com_arr)                                   # array with complex numbers and getting real and imaginary parts
for i in range(len(com_arr)):
    print("Real value:", com_arr[i].real)
    print("imaginary value:", com_arr[i].imag)

[1.        +0.j         0.70710678+0.70710678j]
Real value: 1.0
imaginary value: 0.0
Real value: 0.70710678
imaginary value: 0.70710678


In [19]:
# 1. Write a Python program to find the number of elements of an array, length of one array element in bytes
# and total bytes consumed by the elements.

arr_list = [10,20,30,40]
arr = numpy.array(arr_list, dtype=int)
print("Size of array:", arr.size)               
print("size of each element in bytes:", arr.itemsize)
print("Length of array in bytes:", arr.nbytes)

Size of array: 4
size of each element in bytes: 4
Length of array in bytes: 16


In [20]:
# 12. Write a Python program to find common values between two arrays

array1 = numpy.array([10,20,30,40])
array2 = numpy.array([10,40,60,80,90])           
same_ele = numpy.intersect1d(array1, array2)
print("Elements same in both arrays:", same_ele)

Elements same in both arrays: [10 40]


In [21]:
# 13. Write a Python program to find the set difference of two arrays. 
# The set difference will return the sorted, unique values in array1 that are not in array2

array1 = numpy.array([0,10,20,40,60,80])
array2 = numpy.array([10,30,40,50,70,90])               
set_diff = numpy.setdiff1d(array1, array2)
print("Elements present in array1 not in array2 are:", set_diff)

Elements present in array1 not in array2 are: [ 0 20 60 80]


In [22]:
# 14. Write a Python program to find the set exclusive-or of two arrays. 
# Set exclusive-or will return the sorted, unique values that are in only one (not both) of the 

arr1 = numpy.array([0,10,20,40,60,80])
arr2 = numpy.array([10,30,40,50,70])                    
unique_val = numpy.setxor1d(arr1, arr2)
print("uniques values present in both arrays are:", unique_val)

uniques values present in both arrays are: [ 0 20 30 50 60 70 80]


In [24]:
# 15. Write a Python program compare two arrays using numpy. 


arr1 = numpy.array([1,2,3])
arr2 = numpy.array([4,5,6])                     # checking equality of two errors if size, elements both sare same
equal = numpy.array_equal(arr1, arr2)           # returns true else returns false
print(arr1)
print(arr2)
print(equal)                                        
print("arr1 > arr2:")                           # prints true if element in array1 is greater than array2 else prints false
print(numpy.greater(arr1, arr2))
print("arr1 >= arr2:")
print(numpy.greater_equal(arr1, arr2))          # prints true if ele in first array is greater or equal to ele in 2nd array
print("arr1 < arr2:")
print(numpy.less(arr1, arr2))                   # prints true for element is less than ele in second array
print("arr1 <= arr2:")                          # prints true for element is less than or equal to ele in second array
print(numpy.less_equal(arr1, arr2))   

[1 2 3]
[4 5 6]
False
arr1 > arr2:
[False False False]
arr1 >= arr2:
[False False False]
arr1 < arr2:
[ True  True  True]
arr1 <= arr2:
[ True  True  True]


In [25]:
# 16. Write a Python program to save a NumPy array to a text file.

list = [10,20,30,40,50,60]
arr = numpy.array(list)
print(arr)
file = open("file.txt", "w+")              # saving numpy array to text file
content = str(arr)
file.write(content)
file.close()
file = open("file.txt","r")               # displaying content in text file
content = file.read()
print("Content in text file:",content)

[10 20 30 40 50 60]
Content in text file: [10 20 30 40 50 60]


In [6]:

list1 = [1,2,3,4,5]
arr_list = numpy.array(list1)                # writing into text file using numpy functions
print(arr_list)
numpy.savetxt("file1.txt", arr_list,fmt='%s')
content = numpy.loadtxt('file1.txt')        # displaying the text file content
print("Content in text file:",content) 

[1 2 3 4 5]
Content in text file: [1. 2. 3. 4. 5.]


In [27]:
# 17.  Write a Python program to create a contiguous flattened array. 

list_ele = [[1,2,3],[4,5,6]]
arr = numpy.array(list_ele)              # displaying normal array
print(arr)
flattened_arr = numpy.ravel(arr)         # coverting to contiguous flattened array
print("Flattened array:", flattened_arr)

[[1 2 3]
 [4 5 6]]
Flattened array: [1 2 3 4 5 6]


In [28]:
#18.  Write a Python program to change the data type of an array. 

arr = numpy.array([1,2,3,4])
print(arr)                              # displaying type of array
print(arr.dtype)
new_arr = arr.astype(numpy.float64)
print(new_arr)                          # changing int type to float
print("New array type:",new_arr.dtype)

[1 2 3 4]
int32
[1. 2. 3. 4.]
New array type: float64


In [29]:
#19. Write a Python program to create a 3-D array with ones on a diagonal and zeros elsewhere. 

array_3d = numpy.zeros((3,3), dtype = int)
numpy.fill_diagonal(array_3d, 1)           # creating 3 d array with 1's on diagnol and zeros else where
print(array_3d)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [11]:
#20. program to print array in below format...
# [[0.0.0]
# [1.0.0] 
# [1.1.0]
# [1.1.1]]

array = numpy.zeros((4,3), dtype = int)    
for i in range(0, len(array)):
    array[i+1::1, i::-2] = 1
# array[1::1, 0::-2] = 1                      
# array[2::1, 1::-2] = 1                      
# array[3::1, 2::-2] = 1                      
print(array)                              

[[0 0 0]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


In [11]:
#21. Write a Python program to concatenate two 2-dimensional arrays. 

arr1 = numpy.array([[1,2,3],[4,5,6]])
arr2 = numpy.array([[7,8,9],[10,11,12]])     #  program to concatenate two 2-dimensional arrays. 
print("array 1\n:",arr1)
print("array 2:\n",arr2)
arr3 = numpy.concatenate((arr1,arr2), axis = 1)
print(arr3)

array 1
: [[1 2 3]
 [4 5 6]]
array 2:
 [[ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [12]:
#22. Write a Python program to make an array immutable (read-only). 

arr = numpy.arange(10)                   
arr.flags.writeable = False
arr[0] = 1

ValueError: assignment destination is read-only

In [18]:
#23. Write a Python program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array. 

arr = numpy.arange(0, 12).reshape(3,4)
print("original array elements:\n",arr)        
print("New array elements are:")
for i in range(len(arr)):
    print(arr[i] * 3)

original array elements:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New array elements are:
[0 3 6 9]
[12 15 18 21]
[24 27 30 33]


In [20]:
#24. Write a Python program to convert a NumPy array into Python list structure.

arr = numpy.array([[0,1],[2,3],[4,5]])
print(arr)
print(type(arr))                              
lis = arr.tolist()
print(lis)
print(type(lis))

[[0 1]
 [2 3]
 [4 5]]
<class 'numpy.ndarray'>
[[0, 1], [2, 3], [4, 5]]
<class 'list'>


In [24]:
#25.  Write a Python program to convert a NumPy array into Python list structure. 

numpy.set_printoptions(precision=3)
arr_ele = numpy.array([0.26153123,0.52760141,0.5718299,0.5927067,0.7831874,0.69746349,0.35399976,0.99469633,0.0694458,0.54711478])
print(arr_ele)

[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


In [26]:
#26. Write a Python program to suppresses the use of scientific notation for small numbers in numpy array.

arr = numpy.array([ 1.60000000e-10,1.60000000e+00,1.20000000e+03,2.35000000e-01])
numpy.set_printoptions(suppress = True)
print(arr)

[   0.       1.6   1200.       0.235]


In [37]:
#27. Write a Python program to how to add an extra column to an numpy array. 

org_arr = numpy.array([[10,20,30],[40,50,60]])
print(org_arr)
new_column = numpy.array([100, 200])            # to add new column to existing array
arr = numpy.column_stack((org_arr, new_column))
print("After adding new column:\n",arr)

[[10 20 30]
 [40 50 60]]
After adding new column:
 [[ 10  20  30 100]
 [ 40  50  60 200]]


In [41]:
#28. Write a Python program to remove specific elements in a numpy array. 

arr = numpy.array([10,20,30,40,50,60,70,80,90,100])
print("original array before deletion:",arr)
index_to_be_del = [1,4,5]
new_arr = numpy.delete(arr,index_to_be_del) 
print("array after deleting at 1,4,5:",new_arr)

original array before deletion: [ 10  20  30  40  50  60  70  80  90 100]
array after deleting at 1,4,5: [ 10  30  40  70  80  90 100]
